### ISSUE TITLE
00-Prerequisites Local Setup: Node/NPM version needs to be <16.10.0-1?

### ISSUE THREAD

**Issue by m-strasser** [inveniosoftware/training#107]
I was unable to install the required npm modules via `./scripts/bootstrap` (or `invenio webpack clean buildall`) using nodejs `16.10.0-1`, but succeeded using nodejs `14.18.0` and `12.22.6`.

Installing with nodejs 16.10.0-1 results in:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: invenio-assets@1.0.0
npm ERR! Found: react-overridable@0.0.2
npm ERR! node_modules/react-overridable
npm ERR!   react-overridable@"^0.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-overridable@"^0.0.3" from react-searchkit@1.0.0-alpha.17
npm ERR! node_modules/react-searchkit
npm ERR!   react-searchkit@"^1.0.0-alpha.12" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/USER/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2021-09-28T14_48_57_934Z-debug.log
Traceback (most recent call last):
  File "/path/to/my/venv/bin/invenio", line 8, in <module>
    sys.exit(cli())
  File "/path/to/my/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/path/to/my/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/my/venv/lib/python3.9/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/my/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/my/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/flask_webpackext/cli.py", line 72, in buildall
    current_webpack.project.buildall()
  File "/path/to/my/venv/lib/python3.9/site-packages/pywebpack/project.py", line 141, in buildall
    super(WebpackTemplateProject, self).buildall()
  File "/path/to/my/venv/lib/python3.9/site-packages/pywebpack/project.py", line 69, in buildall
    self.install()
  File "/path/to/my/venv/lib/python3.9/site-packages/pywebpack/helpers.py", line 48, in inner
    raise RuntimeError("Process exited with code {}".format(exit_code))
RuntimeError: Process exited with code 1
```

**Comment by ntarocco** [comment]
README updated, thank you!
